### ISSUE TITLE
Avoid setInterval and use MutationObserver

### ISSUE THREAD

**Issue by mattiagalati** [kevinwucodes/gmail-quick-links#12]
In your code you make use of `setInterval` to check if left nav panel is loaded, and clear that interval when the dom you need is ready.
I would suggest you to use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) instead, in order to tell the browser to notify your code when the dom is ready.

**Comment by kevinwucodes** [comment]
I've never used MutationObserver before.  I'll look into it, thanks.

**Comment by kevinwucodes** [comment]
I looked at this and it appears that [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) can't observe nodes if that node doesn't already exist.  Not sure if using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) is still achieveable.
