### ISSUE TITLE
Multiple account support broken

### ISSUE THREAD

**Issue by orschiro** [kevinwucodes/gmail-quick-links#19]
Dear @kevinwucodes,

Thank you so much for your extension! It is so helpful. :-)

I have a question. It used to work with multiple accounts. But since two days, the quick links only show up on mail.google.com/mail/u/1/ but no longer on mail.google.com/mail/u/0/. 

Do you have any idea why that could be?

Thank you!

**Comment by kevinwucodes** [comment]
Hi @orschiro, I'm unable to see this behavior.  Are you using the same browser when you are logged in with multiple accounts?  Can you try a different computer and see if you're still getting this behavior?

**Comment by orschiro** [comment]
@kevinwucodes logged out, removed the extension and did several other tweaks. Now it reappeared in both inboxes. Thanks for your help though! :-)

**Comment by orschiro** [comment]
For the record. My issue was related to having changed the name of my Google Account.
