### ISSUE TITLE
Seperate quick links per gmail account

### ISSUE THREAD

**Issue by ugrug** [kevinwucodes/gmail-quick-links#2]
Currently the same quick links displayed for all gmail account.
Should be nice to have different lists for different accounts.

**Comment by kevinwucodes** [comment]
This is a great idea.  I didn't think about this before.

My thinking is that I could possibly use the Gmail APIs to get identity data and then store each quick link per identity.  Then when you switch identities, all the right quick links should get loaded for that identity

I'll see what I can do and get started.

**Comment by ugrug** [comment]
Its a dirty method to find the user as code can change any time..

var as = document.querySelectorAll('a');
for (var i = 0; i < as.length; i++) {
  if (as[i].title.match('^Google Account.*') != null) {
    console.log(as[i].title);
  }
}

**Comment by kevinwucodes** [comment]
I have a preview ready in the multiple branch.  Hope to release this to the next week or so.

https://github.com/kevinwucodes/gmail-quick-links/tree/multiple

**Comment by kevinwucodes** [comment]
#5

**Comment by kevinwucodes** [comment]
merged
