### ISSUE TITLE
Lastest Gmail Update messes with Quick Links

### ISSUE THREAD

**Issue by Cthulzilla** [kevinwucodes/gmail-quick-links#23]
Just noticed yesterday (9/13). The Quick Links side bar and Gmail's side bar are overlapping.
![image](https://user-images.githubusercontent.com/7672326/45548618-fed2da00-b7f2-11e8-89f7-739b28b620a7.png)

**Comment by kevinwucodes** [comment]
fixed in a74730c92f47bc60af7aea8ad24165d82b61bb1d
