### ISSUE TITLE
Compact layout vertically

### ISSUE THREAD

**Issue by nrichards** [kevinwucodes/gmail-quick-links#24]
Thank you for the killer Chrome Extension.

I'm wondering what you think about altering the layout, to make it more compact?

![quick-links-compact](https://user-images.githubusercontent.com/704698/45986977-cb2e5600-c023-11e8-8ea7-71ee259bb663.jpg)

* Moving the "Add Quick Link" DIV into the title label's
* Shorten to just "Add"

**Comment by kevinwucodes** [comment]
Hey @nrichards , thanks for the PR!  I think this looks great!  Before I accept the PR, could you rename the CSS attributes so that they're compatible with React?

Meaning, "align-items" becomes "alignItems"; "justify-content" becomes "justifyContent", etc.

**Comment by nrichards** [comment]
Heyo @kevinwucodes - glad it is to your liking :) 

Renaming now ... is this commit correctly conforming the identifier naming to React-style?

New DIFF: https://github.com/kevinwucodes/gmail-quick-links/pull/25/files

**Comment by kevinwucodes** [comment]
merged

**Comment by nrichards** [comment]
Thanks Kevin :)
