### ISSUE TITLE
Can we get some margin please?

### ISSUE THREAD

**Issue by neillshurville** [kevinwucodes/gmail-quick-links#27]
Such a minor issue, but can we get bottom margin 15px on gmailQuickLinksContainer?

It's so close to the "Inbox" menu item that I keep clicking the wrong thing.

**Comment by kevinwucodes** [comment]
I added 10px to the bottom padding in v0.3.8.  15px seemed a bit too large.

**Comment by neillshurville** [comment]
Thanks Kevin, much more user friendly now. Great job.
