### ISSUE TITLE
Fonts too small

### ISSUE THREAD

**Issue by fireattack** [kevinwucodes/gmail-quick-links#3]
I'm using: Chrome

![image](https://user-images.githubusercontent.com/4130991/30225705-fc87cb76-9498-11e7-89f4-c1b7d3218244.png)

For some reason, the font here is very small compared to what the original lab one has.

The original one has font size of 12.8px, but the one added by extension is only 10.24px.

The funny thing is, the "Add Quick Link" text from extension is 12.8px, while the original is actually smaller (11.2px).

**Comment by kevinwucodes** [comment]
I attempted to copy the styles from the original Labs CSS, but I dont think I captured everything.  If you disable the original Dan P Gmail Labs, the font size should show up with the correct size.

**Comment by kevinwucodes** [comment]
I think this has been fixed.
