### ISSUE TITLE
Quick Links seems to not be loading again this morning

### ISSUE THREAD

**Issue by BillGettys** [kevinwucodes/gmail-quick-links#30]
Chrome 72.0.3626.119

I tried installing the Firefox add-on to see if that one works without success.

 Kevin, we'll be grateful for your help on this again.

**Comment by kevinwucodes** [comment]
Looks like Gmail made a style change.  I'll check this out in a bit.

```
document.querySelectorAll('a[class="gb_x gb_Da gb_f"]')[0].attributes['aria-label']
```

**Comment by drgkt** [comment]
Confirming not working anymore.

**Comment by parautenbach** [comment]
Ditto

Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by JohnKnoepfle** [comment]
Same here

**Comment by kevinwucodes** [comment]
Fixed in 0.3.12

**Comment by Zanatoo** [comment]
Fixed but all my previous quick links are gone :(

**Comment by drgkt** [comment]
"Fixed but all my previous quick links are gone :("
I second that! :-(
