### ISSUE TITLE
Add compatibility with "Simplify Gmail" extension

### ISSUE THREAD

**Issue by nrichards** [kevinwucodes/gmail-quick-links#33]
Currently if both this and Simplify Gmail are installed, and the S.G. "hide all stuff" hamburger menu is enabled, the Gmail Quick Links DIV is squished vertically.

Workaround is to decorate Gmail Quick Links' DIV with classes found in one of the DIVs encapsulating the Labels and Hangouts DIV.

Simplify Gmail extension: https://chrome.google.com/webstore/detail/simplify-gmail/pbmlfaiicoikhdbjagjbglnbfcbcojpj?hl=en
Source: https://github.com/leggett/simplify/tree/master/gmail

See the attached image for illustration of problem and workaround.

To fix for realz, I might also reach out to the Simplify Gmail extension author @leggett, and coordinate on "the best solution."

<3

![GmailQL-Simplify-Compatibility](https://user-images.githubusercontent.com/704698/56771026-58788b00-676a-11e9-95a6-8f2a1307d863.png)

**Comment by leggett** [comment]
FWIW, I set the width of the nav to zero when the nav is hidden instead of display:none b/c I need the compose button to still be visible so I can move it to the bottom-right of the screen.

**Comment by kevinwucodes** [comment]
@nrichards thank you for the in-depth analysis!  I hadn't heard of the Simplify Gmail extension and I think I was able to fix this.  The fix is that during the collapse of the sidebar, the quick links extension should disappear completely.  If so, this should be fixed in v0.3.14.

**Comment by kevinwucodes** [comment]
@leggett thanks for the background on this!  Your comment gave me a big hint in helping making the gmail quick links extension compatible with your Simplify Gmail extension.  Great job on that extension, btw!

**Comment by nrichards** [comment]
DROOL, thank you @kevinwucodes! Thank you @leggett! They are working together! 

Closing this ticket.

**Comment by nrichards** [comment]
https://github.com/kevinwucodes/gmail-quick-links/commit/1cfa2b3bed62ba91fcc669aef66fc04ddb7e662d related changes
