### ISSUE TITLE
Quick Links Not Displaying

### ISSUE THREAD

**Issue by ulmont** [kevinwucodes/gmail-quick-links#34]
Seems to have been a breaking update between May 15, 2019 and May 16, 2019.

The console reports that "Loaded Gmail Quick Links".

document.getElementById('gmailQuickLinksContainer') reports a div, but that div is 256x0.

![image](https://user-images.githubusercontent.com/25596585/57861472-4bc0e300-77bc-11e9-9132-2df6920fa693.png)

**Comment by sergoulpus** [comment]
Same here.

**Comment by survivor303** [comment]
Same!

**Comment by BillGettys** [comment]
Same

**Comment by sdbrit71** [comment]
Same

**Comment by kevinwucodes** [comment]
Looks like Gmail had another style change in their 5/16/19 update.  This should be fixed in v0.3.15 (f0c4395).
