### ISSUE TITLE
Google did it again

### ISSUE THREAD

**Issue by Cthulzilla** [kevinwucodes/gmail-quick-links#35]
Sorry! I really hate it when this happens to you!

Apparently, Google made some changes and broke your extension, again.

**Comment by ulmont** [comment]
Yes.  The same as 5/16 - "Loaded Gmail Quick Links" is present in the console and the "document.getElementById('gmailQuickLinksContainer')" div exists but is 256x0.

**Comment by kevinwucodes** [comment]
Yup, the styles in Gmail got changed again.  Fixed in ed16ed1 (v0.3.16).  Currently the new version is in "Pending Review" on the developer dashboard.  I'm hoping the review timeframe will be quick.
