### ISSUE TITLE
Quick Links has disappeared yet again

### ISSUE THREAD

**Issue by BillGettys** [kevinwucodes/gmail-quick-links#37]
Whacked by another Google upgrade, I suspect.

**Comment by ulmont** [comment]
Relevant console output:

Loaded Gmail Quick Links
chrome-extension://ecbkcjeoffcjnppapdlncohmehhnfibd/dist.gmailquicklinks.bundle.js:89 Uncaught TypeError: Cannot read property 'attributes' of null
    at gmailAccountName (chrome-extension://ecbkcjeoffcjnppapdlncohmehhnfibd/dist.gmailquicklinks.bundle.js:89)
    at injectReact (chrome-extension://ecbkcjeoffcjnppapdlncohmehhnfibd/dist.gmailquicklinks.bundle.js:170)
    at chrome-extension://ecbkcjeoffcjnppapdlncohmehhnfibd/dist.gmailquicklinks.bundle.js:218

**Comment by tedepstein** [comment]
Broken for me as well.

**Comment by kevinwucodes** [comment]
This should be fixed in v0.3.17, which should be published in the Chrome Store shortly.

**Comment by tedepstein** [comment]
Thanks for the quick turnaround, @kevinwucodes !
