### ISSUE TITLE
Extension not working in Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by blizzo521** [kevinwucodes/gmail-quick-links#39]
A couple of days ago I noticed that the extension stopped working and I can no longer see my quick links.  

**Environment info:**
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
OS: iOS 10.14.5 (18F132)
Hardware: MacBook Pro (15-inch, 2016)

**Console output:**
```
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
index.js:36 Loaded Gmail Quick Links
gmailNodes.js:8 Uncaught TypeError: Cannot read property 'attributes' of null
    at gmailAccountName (gmailNodes.js:8)
    at injectReact (index.js:41)
    at index.js:89
```

Please let me know if there is anything else I can do to help debug this issue!

**Comment by kevinwucodes** [comment]
Hi @blizzo521 , this was fixed in v0.3.17 due to a gmail update.  If you update your gmail quick links, your links should come back.
