### ISSUE TITLE
Gmail changed layout again

### ISSUE THREAD

**Issue by ulmont** [kevinwucodes/gmail-quick-links#40]
Same as a couple of days ago.  The Loaded Gmail Quick Links succeeds, but then the query selector returns null.

![image](https://user-images.githubusercontent.com/25596585/61310569-2c453700-a7ba-11e9-9c63-47098b58b48c.png)

**Comment by kevinwucodes** [comment]
Thanks @ulmont for the heads up.  This has been fixed again, in v0.3.18, this time with more robust selectors so hopefully if gmail goes through another style change, the robust selector will automatically adjust to the new changes.
