### ISSUE TITLE
is there a limit to how many quickLinks we can have

### ISSUE THREAD

**Issue by jad00gar** [kevinwucodes/gmail-quick-links#43]
I currently have 15 QuickLinks. and if I add more I don't see them show up.
Questions:
1- is there a limit to how many we can have
2- is this something I can change to allow more

**Comment by kevinwucodes** [comment]
There isn't a limit to the number you could have.  But if you have too many quick links, it'll push down the other links like inbox, starred, snoozed that gmail already gives you

Are you using another extension in gmail?  Could that be what's causing you to see less than 15 quick links?

**Comment by jad00gar** [comment]
I don't have any other extensions for gmail this is the only one. but if i try to add more then 15 it just doesn't work
