### ISSUE TITLE
Gmail GUI updated quicklink is not working anymore

### ISSUE THREAD

**Issue by jad00gar** [kevinwucodes/gmail-quick-links#52]
Hello,
Gmail gui upgraded today and quick link is no longer working for me.
can you please advise if there is anything I can do to fix it.

thanks

**Comment by jad00gar** [comment]
Actually it's working intermittingly.

**Comment by alexspeller** [comment]
Logging out and logging in again fixed it for me with the new design.

Duplicate of #51

**Comment by kevinwucodes** [comment]
I'm unable to reproduce this error.  Closing this issue for now.  Please open a new issue if this continues to occur.
